defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_


model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  save_top_k: 5
  auto_insert_metric_name: False
  save_on_train_epoch_end: True
  start_save_epoch: 5

early_stopping:
  monitor: "val/loss"
  patience: 5e-5
  mode: "min"

model_summary:
  max_depth: -1

lr_monitor:
  logging_interval: 'step'
  log_momentum: true
  log_weight_decay: true